DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS INSTRUMENT;
DROP TABLE IF EXISTS PERFORMANCE_PARTICIPANTS;
DROP TABLE IF EXISTS PERFORMANCE;
DROP TABLE IF EXISTS COMPOSITION;


CREATE TABLE STUDENT (
       ID INT NOT NULL AUTO_INCREMENT
     , INSTRUMENT_ID INT
     , FIRST_NAME VARCHAR(99) NOT NULL
     , LAST_NAME VARCHAR(99) NOT NULL
     , BIRTH_DATE DATE
);

CREATE TABLE INSTRUMENT (
       ID INT NOT NULL AUTO_INCREMENT
     , TYPE VARCHAR(99) NOT NULL
     , PRODUCER VARCHAR(99) NOT NULL
     , PROD_DATE DATE
     , PURCH_DATE DATE
);

CREATE TABLE PERFORMANCE_PARTICIPANTS (
      PERFORMANCE_ID INT NOT NULL
    , STUDENT_ID INT NOT NULL
);

CREATE TABLE PERFORMANCE (
      ID INT NOT NULL
    , COMPOSITION_ID INT NOT NULL
);

CREATE TABLE COMPOSITION (
      ID INT NOT NULL
    , TITLE VARCHAR(99) NOT NULL
    , AUTHOR VARCHAR(99)
);




